# Generated by Django 5.1.3 on 2024-11-14 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WasteData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_id', models.IntegerField()),
                ('country_name', models.CharField(max_length=255)),
                ('gdp', models.FloatField()),
                ('food_waste', models.FloatField()),
                ('glass_waste', models.FloatField()),
                ('metal_waste', models.FloatField()),
                ('other_waste', models.FloatField()),
                ('paper_waste', models.FloatField()),
                ('plastic_waste', models.FloatField()),
                ('rubber_waste', models.FloatField()),
                ('wood_waste', models.FloatField()),
                ('garden_waste', models.FloatField()),
                ('agricultural_waste', models.FloatField()),
                ('construction_waste', models.FloatField()),
                ('ewaste', models.FloatField()),
                ('hazardous_waste', models.FloatField()),
                ('industrial_waste', models.FloatField()),
                ('medical_waste', models.FloatField()),
                ('total_msw', models.FloatField()),
                ('waste_collection_urban_area_percent', models.FloatField()),
                ('waste_collection_urban_households_percent', models.FloatField()),
                ('waste_collection_urban_population_percent', models.FloatField()),
                ('waste_collection_urban_waste_percent', models.FloatField()),
                ('anaerobic_digestion_percent', models.FloatField()),
                ('compost_percent', models.FloatField()),
                ('controlled_landfill_percent', models.FloatField()),
                ('incineration_percent', models.FloatField()),
                ('recycling_percent', models.FloatField()),
                ('info_system', models.CharField(max_length=255)),
                ('national_agency', models.CharField(max_length=255)),
                ('national_law', models.CharField(max_length=255)),
                ('public_info', models.TextField()),
                ('population', models.IntegerField()),
                ('waste_collection_coverage_total_percent', models.FloatField()),
            ],
        ),
    ]
