# Generated by Django 5.1.3 on 2024-11-14 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wastedata',
            name='region_id',
            field=models.CharField(max_length=10),
        ),
    ]
