# Generated by Django 5.1.3 on 2024-11-14 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_category_points_units_finaluser_points_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finaluser',
            name='points',
        ),
        migrations.AddField(
            model_name='points',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='points', to='security.finaluser'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='security.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='units',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='security.units'),
        ),
    ]
