# Generated by Django 5.1.3 on 2024-11-15 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0003_remove_finaluser_points_points_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='points',
            name='user',
        ),
        migrations.RemoveField(
            model_name='product',
            name='units',
        ),
        migrations.RemoveField(
            model_name='finaluser',
            name='is_admin_user',
        ),
        migrations.AddField(
            model_name='finaluser',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='finaluser',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AddField(
            model_name='finaluser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, verbose_name='Número de teléfono'),
        ),
        migrations.AddField(
            model_name='finaluser',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/', verbose_name='Imagen de perfil'),
        ),
        migrations.AddField(
            model_name='finaluser',
            name='role',
            field=models.CharField(choices=[('USER', 'Usuario'), ('ADMIN', 'Administrador')], default='USER', max_length=5),
        ),
        migrations.AlterField(
            model_name='finaluser',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.DeleteModel(
            name='AdminUser',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Points',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Units',
        ),
    ]
