# Generated by Django 5.1.3 on 2024-11-15 16:49

import core.security.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0005_user_delete_finaluser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='Imagen de perfil del usuario.', null=True, upload_to='profile_img/', validators=[core.security.models.validate_image_extension]),
        ),
    ]
