# Generated by Django 5.1.3 on 2024-11-15 12:44

import core.dashboard.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_product_name_alter_product_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pointhistory',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='points',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='points',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='points',
            name='action_type',
            field=models.CharField(choices=[('TASK_COMPLETED', 'Tarea Completada'), ('PRODUCT_REQUEST', 'Solicitud de Producto'), ('PURCHASE', 'Compra Realizada'), ('PENALTY', 'Penalización')], default=2, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='products/', validators=[core.dashboard.models.validate_image_extension]),
        ),
        migrations.CreateModel(
            name='ProductRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('APPROVED', 'Aprobada'), ('DENIED', 'Denegada')], default='PENDING', max_length=10)),
                ('points_assigned', models.PositiveIntegerField(blank=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='dashboard.product')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud de Producto',
                'verbose_name_plural': 'Solicitudes de Producto',
            },
        ),
    ]
