# Generated by Django 5.1.3 on 2024-11-15 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_reward'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
    ]
